<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('products',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->string('slug')->unique(),$t->string('name'),$t->boolean('active')->default(true)]));
Schema::create('plans',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->foreignUuid('product_id')->constrained(),$t->string('name'),$t->unsignedTinyInteger('level'),$t->unsignedBigInteger('price_minor'),$t->string('currency',3)->default('TRY'),$t->boolean('visible')->default(true),$t->unique(['product_id','level'])]));
Schema::create('plan_entitlements',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->foreignUuid('plan_id')->constrained()->cascadeOnDelete(),$t->string('key'),$t->json('value'),$t->unique(['plan_id','key'])]));
Schema::create('projects',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->string('name'),$t->string('company_name'),$t->string('website_url')->nullable(),$t->string('industry')->nullable(),$t->string('status')->default('active'),$t->softDeletes()]));
Schema::create('competitors',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('project_id')->constrained(),$t->string('company_name'),$t->string('domain')->nullable(),$t->string('country',2)->nullable(),$t->string('language',8)->nullable(),$t->string('industry')->nullable(),$t->text('description')->nullable(),$t->json('tags')->nullable(),$t->text('notes')->nullable(),$t->string('status')->default('active'),$t->timestamp('last_analyzed_at')->nullable(),$t->timestamp('last_successful_crawl_at')->nullable(),$t->text('last_error')->nullable(),$t->softDeletes(),$t->index(['organization_id','project_id','status'])]));
Schema::create('competitor_sources',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('competitor_id')->constrained()->cascadeOnDelete(),$t->string('platform'),$t->string('external_id')->nullable(),$t->string('url'),$t->boolean('active')->default(true),$t->unique(['competitor_id','platform','url'])]));
Schema::create('subscriptions',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('product_id')->constrained(),$t->foreignUuid('plan_id')->constrained(),$t->string('status'),$t->string('billing_period'),$t->timestamp('starts_at'),$t->timestamp('ends_at')->nullable(),$t->timestamp('next_payment_at')->nullable(),$t->timestamp('cancelled_at')->nullable(),$t->boolean('auto_renew')->default(true),$t->unsignedBigInteger('price_snapshot_minor'),$t->json('limits_snapshot'),$t->index(['organization_id','product_id','status'])]));
Schema::create('subscription_items',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->foreignUuid('subscription_id')->constrained()->cascadeOnDelete(),$t->string('provider_item_id')->nullable(),$t->unsignedInteger('quantity')->default(1),$t->json('metadata')->nullable()]));
Schema::create('billing_cycles',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('subscription_id')->constrained(),$t->timestamp('starts_at'),$t->timestamp('ends_at'),$t->string('status'),$t->unique(['subscription_id','starts_at'])]));
Schema::create('payments',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('subscription_id')->nullable()->constrained(),$t->string('provider'),$t->string('provider_id')->unique(),$t->unsignedBigInteger('amount_minor'),$t->string('currency',3),$t->string('status'),$t->json('metadata')->nullable(),$t->timestamp('paid_at')->nullable()]));
Schema::create('payment_webhooks',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->string('provider'),$t->string('event_id'),$t->string('type'),$t->json('payload'),$t->timestamp('processed_at')->nullable(),$t->unique(['provider','event_id'])]));
Schema::create('refunds',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('payment_id')->constrained(),$t->string('provider_id')->nullable(),$t->unsignedBigInteger('amount_minor'),$t->string('status'),$t->text('reason')->nullable()]));
Schema::create('topup_products',fn(Blueprint $t)=>$this->base($t,fn($t)=>[$t->foreignUuid('product_id')->nullable()->constrained(),$t->string('credit_type'),$t->decimal('credits',16,4),$t->unsignedBigInteger('price_minor'),$t->unsignedSmallInteger('expires_months')->nullable(),$t->boolean('active')->default(true)]));
Schema::create('topup_purchases',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('topup_product_id')->constrained(),$t->foreignUuid('payment_id')->nullable()->constrained(),$t->string('status'),$t->timestamp('credited_at')->nullable()]));
Schema::create('credit_wallets',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('product_id')->nullable()->constrained(),$t->string('credit_type'),$t->decimal('subscription_balance',16,4)->default(0),$t->decimal('promotion_balance',16,4)->default(0),$t->decimal('purchased_balance',16,4)->default(0),$t->decimal('reserved_balance',16,4)->default(0),$t->unique(['organization_id','product_id','credit_type'])]));
Schema::create('credit_ledger',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('user_id')->nullable()->constrained(),$t->foreignUuid('wallet_id')->constrained('credit_wallets'),$t->foreignUuid('product_id')->nullable()->constrained(),$t->string('credit_type'),$t->string('transaction_type'),$t->decimal('amount',16,4),$t->decimal('previous_balance',16,4),$t->decimal('next_balance',16,4),$t->nullableMorphs('reference'),$t->string('idempotency_key')->unique(),$t->text('description'),$t->timestamp('occurred_at')->index()]));
Schema::create('credit_reservations',fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->foreignUuid('wallet_id')->constrained('credit_wallets'),$t->decimal('estimated_amount',16,4),$t->decimal('actual_amount',16,4)->nullable(),$t->string('status'),$t->string('idempotency_key')->unique(),$t->timestamp('expires_at')]));
$this->generic(['usage_events','integration_settings','apify_actors','apify_runs','analysis_jobs','website_pages','website_snapshots','website_changes','social_profiles','social_contents','social_content_metrics','social_comments','metric_summaries','ai_providers','ai_models','ai_usage_records','ai_analyses','evidence_sources','recommendations','reports','alerts','notifications','audit_logs','security_events','system_settings']);
Schema::create('jobs',function(Blueprint $t){$t->bigIncrements('id');$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});Schema::create('job_batches',function(Blueprint $t){$t->string('id')->primary();$t->string('name');$t->integer('total_jobs');$t->integer('pending_jobs');$t->integer('failed_jobs');$t->longText('failed_job_ids');$t->mediumText('options')->nullable();$t->integer('cancelled_at')->nullable();$t->integer('created_at');$t->integer('finished_at')->nullable();});Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});Schema::create('cache',function(Blueprint $t){$t->string('key')->primary();$t->mediumText('value');$t->integer('expiration');});Schema::create('cache_locks',function(Blueprint $t){$t->string('key')->primary();$t->string('owner');$t->integer('expiration');});
}private function generic(array $names):void{foreach($names as $name)Schema::create($name,fn(Blueprint $t)=>$this->tenant($t,fn($t)=>[$t->string('type')->nullable(),$t->string('status')->nullable(),$t->string('external_id')->nullable(),$t->foreignUuid('project_id')->nullable(),$t->foreignUuid('competitor_id')->nullable(),$t->json('data')->nullable(),$t->longText('content')->nullable(),$t->timestamp('occurred_at')->nullable(),$t->softDeletes(),$t->index(['organization_id','status','created_at'])]));}private function base(Blueprint $t,callable $fields):void{$t->uuid('id')->primary();$fields($t);$t->timestamps();}private function tenant(Blueprint $t,callable $fields):void{$t->uuid('id')->primary();$t->foreignUuid('organization_id')->constrained()->cascadeOnDelete();$fields($t);$t->timestamps();}public function down():void{Schema::dropAllTables();}};
